backend = "redis";
servers = "redis:6379";
autolearn = true;
per_user = true;
users_enabled = true;

statfile {
    symbol = "BAYES_SPAM";
    spam = true;
}
statfile {
    symbol = "BAYES_HAM";
    spam = false;
}
