rule "local" {
    servers = "localhost:11335";
    symbol = "TELEGRAM_FUZZY";
    max_score = 10.0;
    mime_types = ["*"];
    read_only = false;
    skip_unknown = true;
    fuzzy_map = {
        TELEGRAM_FUZZY_DENIED {
            max_score = 10.0;
            flag = 1;
        }
    }
}
